### ISSUE TITLE
Landing page layout

### ISSUE THREAD

**Issue by bulbil** [swat-ds/theme-foundation-ecr#3]
Layout and styles for a two column landing page as per SPEED theme (see layouts wireframes on Slack).

Though I'm wondering if we might try something different that let's the background image come through more and maybe allows for a larger carousel for featured images/items.

- [x] Add scroll down fade in/out to carousel
- [x] Add some styling to background color in carousel <div>

**Comment by betovargas** [comment]
Adds some styling to the footer #4 to test scroll down fade in functionality

**Comment by bulbil** [comment]
Maybe add contrast to landing page text
